openapi: 3.1.0
info:
  title: Agent Runtime API
  version: 0.1.0-draft
  summary: A workflow-first agent runtime API (runs, events, artifacts, HITL).
  description: |
    Draft API contract for running agent workflows via SDKs across languages.
    - Prefer structured inputs/outputs (JSON) with discoverable JSON Schemas.
    - Provide streaming observability via Server-Sent Events (SSE).
    - Support Human-in-the-Loop (HITL) checkpoints as first-class resources.
servers:
  - url: https://agent-runtime.example.com
security:
  - bearerAuth: []
tags:
  - name: Runs
  - name: Events
  - name: Workflows
  - name: HITL
  - name: Artifacts
paths:
  /v1/runs:
    post:
      tags: [Runs]
      operationId: createRun
      summary: Create a run
      description: Starts a workflow run with JSON input and optional context.
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunCreateRequest"
      responses:
        "201":
          description: Run created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunCreateResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
    get:
      tags: [Runs]
      operationId: listRuns
      summary: List runs
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Cursor"
        - name: status
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/RunStatus"
        - name: workflow_name
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Runs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunListResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/runs/{run_id}:
    get:
      tags: [Runs]
      operationId: getRun
      summary: Get a run
      parameters:
        - $ref: "#/components/parameters/RunId"
      responses:
        "200":
          description: Run
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Run"
        default:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      tags: [Runs]
      operationId: cancelRun
      summary: Cancel a run
      description: Best-effort cancellation; cancellation might not be immediate.
      parameters:
        - $ref: "#/components/parameters/RunId"
      responses:
        "202":
          description: Cancellation requested
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Run"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/runs/{run_id}/events:
    get:
      tags: [Events]
      operationId: getRunEvents
      summary: Stream or fetch run events
      description: |
        If the client sends `Accept: text/event-stream`, the server SHOULD stream events via SSE.
        Otherwise the server MAY return a paginated JSON list of events.
      parameters:
        - $ref: "#/components/parameters/RunId"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Cursor"
      responses:
        "200":
          description: |
            Either a JSON list of events OR an SSE stream (depending on Accept header).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventListResponse"
            text/event-stream:
              schema:
                type: string
              examples:
                sse:
                  summary: SSE payload (each event is JSON in data)
                  value: |
                    event: run.started
                    data: {"event_id":"evt_1","ts":"2025-01-01T00:00:00Z","type":"run.started","run_id":"run_1","payload":{"workflow":{"name":"daily-brief","version":"1.0.0"}}}

                    event: step.completed
                    data: {"event_id":"evt_2","ts":"2025-01-01T00:00:01Z","type":"step.completed","run_id":"run_1","step_id":"facts","payload":{"ok":true}}
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/runs/{run_id}/human/{checkpoint_id}/approve:
    post:
      tags: [HITL]
      operationId: approveCheckpoint
      summary: Approve a HITL checkpoint
      parameters:
        - $ref: "#/components/parameters/RunId"
        - $ref: "#/components/parameters/CheckpointId"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckpointDecisionRequest"
      responses:
        "200":
          description: Checkpoint updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumanCheckpoint"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/runs/{run_id}/human/{checkpoint_id}/reject:
    post:
      tags: [HITL]
      operationId: rejectCheckpoint
      summary: Reject a HITL checkpoint
      parameters:
        - $ref: "#/components/parameters/RunId"
        - $ref: "#/components/parameters/CheckpointId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckpointDecisionRequest"
      responses:
        "200":
          description: Checkpoint updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumanCheckpoint"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/runs/{run_id}/human/{checkpoint_id}/provide_input:
    post:
      tags: [HITL]
      operationId: provideCheckpointInput
      summary: Provide input for a HITL checkpoint
      parameters:
        - $ref: "#/components/parameters/RunId"
        - $ref: "#/components/parameters/CheckpointId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckpointInputRequest"
      responses:
        "200":
          description: Checkpoint updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumanCheckpoint"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/workflows:
    get:
      tags: [Workflows]
      operationId: listWorkflows
      summary: List workflows
      parameters:
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Cursor"
        - name: tag
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Workflows
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowListResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/workflows/{name}:
    get:
      tags: [Workflows]
      operationId: getWorkflow
      summary: Get workflow metadata
      parameters:
        - $ref: "#/components/parameters/WorkflowName"
        - name: version
          in: query
          required: false
          schema:
            type: string
          description: If omitted, returns the default (latest stable) version.
      responses:
        "200":
          description: Workflow
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workflow"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/workflows/{name}/schemas:
    get:
      tags: [Workflows]
      operationId: getWorkflowSchemas
      summary: Get workflow JSON Schemas (input/output/context/artifacts)
      parameters:
        - $ref: "#/components/parameters/WorkflowName"
        - name: version
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Schema bundle
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchemaBundle"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /v1/artifacts/{artifact_id}:
    get:
      tags: [Artifacts]
      operationId: getArtifact
      summary: Get artifact metadata (and download URL for files)
      parameters:
        - $ref: "#/components/parameters/ArtifactId"
      responses:
        "200":
          description: Artifact
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artifact"
        default:
          $ref: "#/components/responses/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    RunId:
      name: run_id
      in: path
      required: true
      schema:
        type: string
        examples: ["run_01J0..."]
    CheckpointId:
      name: checkpoint_id
      in: path
      required: true
      schema:
        type: string
        examples: ["chk_01J0..."]
    WorkflowName:
      name: name
      in: path
      required: true
      schema:
        type: string
    ArtifactId:
      name: artifact_id
      in: path
      required: true
      schema:
        type: string
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 200
        default: 50
    Cursor:
      name: cursor
      in: query
      required: false
      schema:
        type: string
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: false
      schema:
        type: string
      description: Safe retries for createRun and other side-effect calls.
  responses:
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  schemas:
    JsonValue:
      description: Arbitrary JSON value.
      oneOf:
        - type: "null"
        - type: boolean
        - type: number
        - type: string
        - type: array
          items: { $ref: "#/components/schemas/JsonValue" }
        - type: object
          additionalProperties: { $ref: "#/components/schemas/JsonValue" }

    RunStatus:
      type: string
      enum: [queued, running, waiting_human, succeeded, failed, canceled, timed_out]

    WorkflowRef:
      type: object
      required: [name]
      properties:
        name: { type: string }
        version:
          type: string
          description: Semantic version (recommended) or opaque revision.

    Cost:
      type: object
      properties:
        total_tokens: { type: integer, minimum: 0 }
        prompt_tokens: { type: integer, minimum: 0 }
        completion_tokens: { type: integer, minimum: 0 }
        total_usd: { type: number, minimum: 0 }

    Timing:
      type: object
      properties:
        created_at: { type: string, format: date-time }
        started_at: { type: string, format: date-time }
        finished_at: { type: string, format: date-time }
        wall_ms: { type: integer, minimum: 0 }

    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message, retryable]
          properties:
            code: { type: string, examples: ["unauthorized", "validation_error", "tool_error"] }
            message: { type: string }
            retryable: { type: boolean }
            details:
              $ref: "#/components/schemas/JsonValue"

    ArtifactType:
      type: string
      enum: [message, record, file]

    Artifact:
      type: object
      required: [artifact_id, type, created_at]
      properties:
        artifact_id: { type: string }
        type: { $ref: "#/components/schemas/ArtifactType" }
        name: { type: string }
        created_at: { type: string, format: date-time }
        mime_type: { type: string, examples: ["application/json", "text/markdown", "application/pdf"] }
        data:
          description: Present for message/record artifacts; omitted for file artifacts.
          $ref: "#/components/schemas/JsonValue"
        file:
          type: object
          description: Present for file artifacts.
          properties:
            download_url:
              type: string
              format: uri
              description: Pre-signed URL or authenticated download endpoint.
            expires_at: { type: string, format: date-time }
            size_bytes: { type: integer, minimum: 0 }
            sha256: { type: string }

    ArtifactRef:
      type: object
      required: [artifact_id, type]
      properties:
        artifact_id: { type: string }
        type: { $ref: "#/components/schemas/ArtifactType" }
        name: { type: string }

    HumanCheckpointStatus:
      type: string
      enum: [required, approved, rejected, input_provided, resolved]

    HumanCheckpoint:
      type: object
      required: [checkpoint_id, run_id, status, created_at]
      properties:
        checkpoint_id: { type: string }
        run_id: { type: string }
        status: { $ref: "#/components/schemas/HumanCheckpointStatus" }
        created_at: { type: string, format: date-time }
        expires_at: { type: string, format: date-time }
        title: { type: string }
        instructions: { type: string }
        required_schema:
          description: JSON Schema describing expected human input (if any).
          $ref: "#/components/schemas/JsonValue"
        provided_input:
          $ref: "#/components/schemas/JsonValue"
        decision:
          type: object
          properties:
            approved: { type: boolean }
            note: { type: string }
            decided_at: { type: string, format: date-time }

    Run:
      type: object
      required: [run_id, workflow, status, timing]
      properties:
        run_id: { type: string }
        workflow: { $ref: "#/components/schemas/WorkflowRef" }
        status: { $ref: "#/components/schemas/RunStatus" }
        trace_id: { type: string }
        tenant_id: { type: string }
        timing: { $ref: "#/components/schemas/Timing" }
        input:
          description: Original run input (optionally redacted by policy).
          $ref: "#/components/schemas/JsonValue"
        context:
          description: Optional run context (optionally redacted by policy).
          $ref: "#/components/schemas/JsonValue"
        output:
          description: Final output if succeeded.
          $ref: "#/components/schemas/JsonValue"
        error:
          description: Error if failed/canceled/timed_out.
          $ref: "#/components/schemas/ErrorResponse"
        cost: { $ref: "#/components/schemas/Cost" }
        artifacts:
          type: array
          items: { $ref: "#/components/schemas/ArtifactRef" }
        checkpoints:
          type: array
          items: { $ref: "#/components/schemas/HumanCheckpoint" }
        metadata:
          type: object
          additionalProperties: { $ref: "#/components/schemas/JsonValue" }

    RunCreateRequest:
      type: object
      required: [workflow, input]
      properties:
        workflow: { $ref: "#/components/schemas/WorkflowRef" }
        input: { $ref: "#/components/schemas/JsonValue" }
        context:
          description: Caller-provided context (e.g., user identity, locale, channel).
          $ref: "#/components/schemas/JsonValue"
        metadata:
          description: Caller-provided metadata for filtering and analytics.
          type: object
          additionalProperties: { $ref: "#/components/schemas/JsonValue" }
        labels:
          description: Low-cardinality labels for indexing/filters.
          type: object
          additionalProperties: { type: string }

    RunCreateResponse:
      type: object
      required: [run]
      properties:
        run: { $ref: "#/components/schemas/Run" }

    RunListResponse:
      type: object
      required: [data]
      properties:
        data:
          type: array
          items: { $ref: "#/components/schemas/Run" }
        next_cursor: { type: string }

    EventType:
      type: string
      enum:
        - run.started
        - run.completed
        - run.failed
        - run.canceled
        - step.started
        - step.completed
        - step.failed
        - tool.called
        - tool.result
        - llm.request
        - llm.response
        - hitl.required
        - hitl.resolved
        - artifact.created

    Event:
      type: object
      required: [event_id, ts, type, run_id, payload]
      properties:
        event_id: { type: string }
        ts: { type: string, format: date-time }
        type: { $ref: "#/components/schemas/EventType" }
        run_id: { type: string }
        step_id: { type: string }
        tool_name: { type: string }
        payload: { $ref: "#/components/schemas/JsonValue" }
        trace:
          type: object
          properties:
            trace_id: { type: string }
            span_id: { type: string }
            parent_span_id: { type: string }

    EventListResponse:
      type: object
      required: [data]
      properties:
        data:
          type: array
          items: { $ref: "#/components/schemas/Event" }
        next_cursor: { type: string }

    CheckpointDecisionRequest:
      type: object
      properties:
        note: { type: string }

    CheckpointInputRequest:
      type: object
      required: [input]
      properties:
        input: { $ref: "#/components/schemas/JsonValue" }
        note: { type: string }

    Workflow:
      type: object
      required: [name]
      properties:
        name: { type: string }
        version: { type: string }
        description: { type: string }
        tags:
          type: array
          items: { type: string }
        default_timeout_ms: { type: integer, minimum: 0 }
        input_schema_ref:
          type: string
          description: Opaque reference usable with /schemas or external registry.
        output_schema_ref:
          type: string
        definition:
          description: Optional workflow definition for display/debug (implementation-specific).
          $ref: "#/components/schemas/JsonValue"

    WorkflowSummary:
      type: object
      required: [name]
      properties:
        name: { type: string }
        version: { type: string }
        description: { type: string }
        tags:
          type: array
          items: { type: string }

    WorkflowListResponse:
      type: object
      required: [data]
      properties:
        data:
          type: array
          items: { $ref: "#/components/schemas/WorkflowSummary" }
        next_cursor: { type: string }

    SchemaBundle:
      type: object
      required: [workflow, schemas]
      properties:
        workflow: { $ref: "#/components/schemas/WorkflowRef" }
        schema_hash:
          type: string
          description: Stable hash for caching and compatibility checks.
        schemas:
          type: object
          description: Named JSON Schemas (draft 2020-12 compatible).
          additionalProperties:
            $ref: "#/components/schemas/JsonValue"
