workflow_id: meeting_prebrief_daily
version: v1.0.0
status: active
owner: Ops / Store Manager
last_updated: 2025-12-30
delivery_channel: wecom
run_timezone: Asia/Shanghai
spec: spec.md
input_schema: input.schema.json
output_schema: output.schema.json
thresholds: ../../../configs/meeting_prebrief_thresholds.yml
rules: rules.yml
